### ISSUE TITLE
要不要先判断是否已经秒杀，再预减库存呢？

### ISSUE THREAD

**Issue by different-ouvivid** [hfbin/Seckill#2]
//预减库存
        long stock = redisService.decr(GoodsKey.getSeckillGoodsStock, "" + goodsId);//10
        if (stock < 0) {
            localOverMap.put(goodsId, true);
            return Result.error(CodeMsg.MIAO_SHA_OVER);
        }
        //判断是否已经秒杀到了
        SeckillOrder order = seckillOrderService.getSeckillOrderByUserIdGoodsId(user.getId(), goodsId);
        if (order != null) {
            return Result.error(CodeMsg.REPEATE_MIAOSHA);
        }

**Comment by hfbin** [comment]
可以提个pr
