### ISSUE TITLE
请问V2分支启动RabbitMQ报错如何解决？

### ISSUE THREAD

**Issue by HollyBean** [hfbin/Seckill#4]
关键报错信息如下：
 #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'seckill.queue' in vhost '/', class-id=50, method-id=10)
项目代码未更改，本地RabbitMQ已安装，并且可以打开Manager的web界面，之前没接触过RabbitMQ，网上搜了许多问题解答， 也是看得有点蒙，希望大佬能解答一下，万分感谢！

**Comment by hfbin** [comment]
看一下你mq得用户权限是怎样的

**Comment by zinwalin** [comment]
我是手动创建这个queue,   "seckill.queue"

**Comment by HollyBean** [comment]
> 我是手动创建这个queue, "seckill.queue"

好的，谢谢。我以前是通过修改代码解决的-.-

**Comment by HollyBean** [comment]
> 看一下你mq得用户权限是怎样的

谢谢，之前就解决了。忘记close了
