### ISSUE TITLE
redis 是否起到了效果？

### ISSUE THREAD

**Issue by iullor** [hfbin/Seckill#5]
SeckillOrderServiceImpl，我看你这里的逻辑，商品的查找更新库存还是直接找的是数据库，那么redis是否很好的发挥了作用呢？

**Comment by iullor** [comment]
我的意思是在性能上

**Comment by aa310958153** [comment]
没看代码 不过没用redis tps上不去吧  我们现在系统就是前端所有走redis

**Comment by chenshimao** [comment]
大佬们有数据库文件吗

**Comment by hfbin** [comment]
本项目是演示教程，其他细节大家可以自行扩展

**Comment by hfbin** [comment]
> 大佬们有数据库文件吗

sql目录下

**Comment by chenshimao** [comment]
您的邮件我已收到。
